export const RRN_SHOW_NOTIFICATION = 'RRN_SHOW_NOTIFICATION';
export const RRN_HIDE_NOTIFICATION = 'RRN_HIDE_NOTIFICATION';
export const RRN_HIDE_ALL_NOTIFICATIONS = 'RRN_HIDE_ALL_NOTIFICATIONS';
export const RRN_SET_NOTIFICATION_HEIGHT = 'RRN_SET_NOTIFICATION_HEIGHT';
