export const RRN_SHOW_NOTIFICATION = 'RRN_SHOW_NOTIFICATION';
export const RRN_HIDE_NOTIFICATION = 'RRN_HIDE_NOTIFICATION';
export const RRN_REMOVE_NOTIFICATION = 'RRN_REMOVE_NOTIFICATION';
export const RRN_HIDE_ALL_NOTIFICATIONS = 'RRN_HIDE_ALL_NOTIFICATIONS';
